version: '3.8'

services:
  # 后端开发服务
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crm-backend-dev
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    networks:
      - crm-network
    restart: unless-stopped
    command: ["python", "main.py"]

  # 前端开发服务
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: crm-frontend-dev
    ports:
      - "5173:5173"
    depends_on:
      - backend-dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - crm-network
    restart: unless-stopped
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

networks:
  crm-network:
    driver: bridge
