version: '3.8'

services:
  # 数据库初始化服务
  db_init:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crm-db-init
    volumes:
      - ./backend/data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/crm_followup.db
    command: ["python", "init_data.py"]
    networks:
      - crm-network

  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crm-backend
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=sqlite:///./data/crm_followup.db
    volumes:
      - ./backend/data:/app/data
    networks:
      - crm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on:
      - db_init

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: crm-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - crm-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  crm-network:
    driver: bridge

volumes:
  crm-data:
    driver: local
